"""
Django settings for shoestore project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&@u3tm4l3n7)v#((is^5!=fbghcbv6+79)(9fy_x-y(og*dgjz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'cart',
    'orders',
    'users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoestore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoestore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shoe_store',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3307',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Đổi từ 'en-us' sang 'vi' (viết tắt của Việt Nam)
LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Sẵn tiện đổi luôn múi giờ về Việt Nam cho chuẩn nhé

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ==========================================
# CẤU HÌNH GIAO DIỆN ADMIN JAZZMIN (TỐI ƯU)
# ==========================================

JAZZMIN_SETTINGS = {
    # 1. Thông tin chung
    "site_title": "Shoe Store Admin",
    "site_header": "Shoe Store",
    "site_brand": "SHOE STORE",
    "welcome_sign": "Hệ thống Quản trị Shoe Store 👟",
    "copyright": "Shoe Store © 2026",

    # 2. Thanh Menu Top (Thêm nút bấm nhanh)
    "topmenu_links": [
        {"name": "Xem trang web",  "url": "/", "new_window": True}, # Click là mở sang trang khách hàng
        {"model": "auth.User"},
    ],

    # 3. Thanh Tìm kiếm siêu tốc (Tìm cả User lẫn Sản phẩm cùng lúc)
    "search_model": ["auth.User", "products.Product"],

    # 4. Gắn icon xịn xò cho từng bảng
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-cog",
        "auth.Group": "fas fa-users",
        "products": "fas fa-box-open",
        "products.Product": "fas fa-shoe-prints",
        "products.Category": "fas fa-tags",
        "products.Brand": "fas fa-copyright",
        "products.Size": "fas fa-ruler",
        "orders": "fas fa-shopping-cart",
        "cart": "fas fa-shopping-basket",
        "users": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # 5. Tinh chỉnh Layout Menu
    "show_sidebar": True,
    "navigation_expanded": False, # Thu gọn menu con cho đỡ rối mắt
    "related_modal_active": True, # Cho phép thêm mới dữ liệu dạng Popup cực tiện
}

# ==========================================
# BẢNG PHỐI MÀU (UI TWEAKS) - PHONG CÁCH SNEAKER
# ==========================================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Phối màu
    "brand_colour": "navbar-dark",         # Nền logo màu đen
    "navbar": "navbar-dark",               # Thanh Topbar màu đen
    "sidebar": "sidebar-dark-danger",      # Menu trái màu đen, khi chọn hiện màu đỏ rực
    "accent": "accent-danger",             # Các nút bấm chính chuyển sang màu đỏ (hợp bán giày)
    "theme": "lumen",                      # Nền bảng dữ liệu màu trắng sáng/sạch sẽ
    
    # Cấu trúc cố định (Scrolling mượt)
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    
    # TÍNH NĂNG ĂN TIỀN NHẤT: Cố định nút LƯU ở trên cùng màn hình
    "actions_sticky_top": True 
    
}
# --- CẤU HÌNH ĐỊNH DẠNG SỐ (THÊM VÀO DƯỚI CÙNG) ---
USE_L10N = False
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3