"""
Django settings for shoestore project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Load environment variables from .env (BASE_DIR/.env)
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Hosts
_hosts = os.getenv('ALLOWED_HOSTS', '')
if _hosts:
    ALLOWED_HOSTS = [h.strip() for h in _hosts.split(',') if h.strip()]
else:
    # Safe defaults for local development and Django test client.
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '[::1]', 'testserver']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products',
    'cart',
    'orders',
    'users',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoestore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoestore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'shoe_store'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use bcrypt as primary hasher (bcrypt rounds configurable via .env)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# Bcrypt rounds (cost factor). Ensure >= 10 for security and performance.
try:
    BCRYPT_ROUNDS = int(os.getenv('BCRYPT_ROUNDS', '12'))
except ValueError:
    BCRYPT_ROUNDS = 12

# REST framework defaults: read-only for anonymous, authenticated for writes
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'],
}

# Simple JWT token settings (lifetimes in days via .env, defaults to 7 days)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=int(os.getenv('ACCESS_TOKEN_DAYS', '7'))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('REFRESH_TOKEN_DAYS', '7'))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Security for HTTPS deployment (set SECURE_SSL_REDIRECT=True in production .env)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Đổi từ 'en-us' sang 'vi' (viết tắt của Việt Nam)
LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'  # Sẵn tiện đổi luôn múi giờ về Việt Nam cho chuẩn nhé

USE_I18N = True
USE_TZ = True

# Force available languages (only Vietnamese for admin/UI)
LANGUAGES = [
    ('vi', 'Tiếng Việt'),
    ('en', 'English'),
]

# Locales directory for custom translations (use `makemessages`/`compilemessages`)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# settings.py

STATIC_URL = 'static/'
# ... (các cấu hình static nếu có)
# Đây là dòng cực kỳ quan trọng để Django "nhìn" thấy thư mục static mày mới tạo
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Nơi gom file khi chạy lệnh collectstatic (để sửa lỗi mày vừa gặp)
STATIC_ROOT = BASE_DIR / "staticfiles"
# ==========================================
# CẤU HÌNH THƯ MỤC LƯU ẢNH (MEDIA)
# ==========================================
# 1. Đường dẫn trên thanh URL của trình duyệt (Ví dụ: 127.0.0.1:8000/media/...)
MEDIA_URL = '/media/'

# 2. Đường dẫn lưu file vật lý vào ổ cứng máy tính
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ==========================================
# CẤU HÌNH GIAO DIỆN ADMIN JAZZMIN (TỐI ƯU)
# ==========================================

JAZZMIN_SETTINGS = {
    # 1. Thông tin chung
    "site_title": "Quản trị Cửa hàng Giày",
    "site_header": "Cửa hàng Giày",
    "site_brand": "CỬA HÀNG GIÀY",
    "welcome_sign": "Chào mừng đến hệ thống quản trị Cửa hàng Giày 👟",
    "copyright": "Cửa hàng Giày © 2026",

    # 2. Thanh Menu Top (Thêm nút bấm nhanh)
    "topmenu_links": [
        {"name": "Xem trang web",  "url": "/", "new_window": True}, # Click là mở sang trang khách hàng
        {"model": "auth.User"},
    ],

    # 3. Thanh Tìm kiếm siêu tốc (Tìm cả User lẫn Sản phẩm cùng lúc)
    "search_model": ["auth.User", "products.Product"],

    # 4. Gắn icon xịn xò cho từng bảng
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-cog",
        "auth.Group": "fas fa-users",
        "products": "fas fa-box-open",
        "products.Product": "fas fa-shoe-prints",
        "products.Category": "fas fa-tags",
        "products.Brand": "fas fa-copyright",
        "products.Size": "fas fa-ruler",
        "orders": "fas fa-shopping-cart",
        "cart": "fas fa-shopping-basket",
        "users": "fas fa-users",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # 5. Tinh chỉnh Layout Menu
    "show_sidebar": True,
    "navigation_expanded": False, # Thu gọn menu con cho đỡ rối mắt
    "related_modal_active": True, # Cho phép thêm mới dữ liệu dạng Popup cực tiện
}

# ==========================================
# BẢNG PHỐI MÀU (UI TWEAKS) - PHONG CÁCH SNEAKER
# ==========================================
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    
    # Phối màu
    "brand_colour": "navbar-dark",         # Nền logo màu đen
    "navbar": "navbar-dark",               # Thanh Topbar màu đen
    "sidebar": "sidebar-dark-danger",      # Menu trái màu đen, khi chọn hiện màu đỏ rực
    "accent": "accent-danger",             # Các nút bấm chính chuyển sang màu đỏ (hợp bán giày)
    "theme": "lumen",                      # Nền bảng dữ liệu màu trắng sáng/sạch sẽ
    
    # Cấu trúc cố định (Scrolling mượt)
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    
    # TÍNH NĂNG ĂN TIỀN NHẤT: Cố định nút LƯU ở trên cùng màn hình
    "actions_sticky_top": True 
    
}
# --- CẤU HÌNH ĐỊNH DẠNG SỐ (THÊM VÀO DƯỚI CÙNG) ---
USE_L10N = False
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ','
NUMBER_GROUPING = 3

# Django REST Framework basic settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# ==========================================
# CẤU HÌNH GỬI EMAIL (QUÊN MẬT KHẨU)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Thay bằng email và mật khẩu ứng dụng của bạn
# Cấu hình trong settings.py

EMAIL_HOST_USER = 'vonhatnam2004@gmail.com' # Email trong ảnh của bạn
EMAIL_HOST_PASSWORD = 'duqy uekr abjt cqdy' # Dán 16 ký tự bạn vừa lấy ở Bước 1 vào đây