# Generated by Django 5.1.1 on 2026-05-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Người đăng ký nhận tin',
                'verbose_name_plural': 'Danh sách Đăng ký nhận tin',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
