# Generated by Django 5.1.1 on 2026-04-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Processing', 'Đang xử lý'), ('Completed', 'Đã thanh toán/Hoàn thành'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
