# Generated by Django 4.2 on 2026-04-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Processing', 'Đang xử lý'), ('Completed', 'Đã thanh toán'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
