# Generated by Django 5.1.1 on 2026-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do đổi/trả'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Processing', 'Đang xử lý'), ('Completed', 'Đã thanh toán/Hoàn thành'), ('Return_Requested', 'Yêu cầu đổi/trả'), ('Returned', 'Đã đổi/trả'), ('Return_Denied', 'Từ chối đổi/trả'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
