# Generated by Django 5.1.1 on 2026-04-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng tại shop', 'verbose_name_plural': 'Đơn hàng tại shop'},
        ),
    ]
