# Generated by Django 5.1.1 on 2026-05-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_0006_alter_order_options_0006_order_return_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_response',
            field=models.TextField(blank=True, null=True, verbose_name='Phản hồi đổi/trả'),
        ),
    ]
