# Generated by Django 5.1.1 on 2026-05-03 07:18

from django.db import migrations, models


def seed_payment_methods(apps, schema_editor):
    PaymentMethodOption = apps.get_model('orders', 'PaymentMethodOption')
    PaymentMethodOption.objects.update_or_create(
        code='COD',
        defaults={'name': 'Thanh toán khi nhận hàng', 'is_active': True},
    )
    PaymentMethodOption.objects.update_or_create(
        code='BANK',
        defaults={'name': 'Chuyển khoản', 'is_active': True},
    )


def rollback_payment_methods(apps, schema_editor):
    PaymentMethodOption = apps.get_model('orders', 'PaymentMethodOption')
    PaymentMethodOption.objects.filter(code__in=['COD', 'BANK']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_return_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
            },
        ),
        migrations.RunPython(seed_payment_methods, rollback_payment_methods),
    ]
