# Generated by Django 5.1.1 on 2026-04-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_options_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storepolicy',
            options={},
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Flash Sale', max_length=120, verbose_name='Tiêu đề chương trình')),
                ('start_date', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Kết thúc')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='sales', to='products.product', verbose_name='Sản phẩm tham gia')),
            ],
            options={
                'verbose_name': 'Chính sách cửa hàng',
                'verbose_name_plural': 'Chính sách cửa hàng',
            },
        ),
    ]
