# Generated by Django 6.0.3 on 2026-03-21 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Giá cũ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Giá hiện tại'),
        ),
    ]
