# Generated by Django 4.2 on 2026-04-22 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_product_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Chương trình khuyến mãi', 'verbose_name_plural': 'Chương trình khuyến mãi'},
        ),
        migrations.AlterModelOptions(
            name='storepolicy',
            options={'verbose_name': 'Chính sách cửa hàng', 'verbose_name_plural': 'Chính sách cửa hàng'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(verbose_name='Nội dung đánh giá'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], default=5, verbose_name='Số sao'),
        ),
    ]
