# Generated by Django 5.1.1 on 2026-04-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discount_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Thương hiệu', 'verbose_name_plural': 'Thương hiệu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Loại sản phẩm', 'verbose_name_plural': 'Loại sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Ảnh sản phẩm', 'verbose_name_plural': 'Ảnh sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Đánh giá', 'verbose_name_plural': 'Đánh giá'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Chương trình khuyến mãi', 'verbose_name_plural': 'Chương trình khuyến mãi'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Kích cỡ', 'verbose_name_plural': 'Kích cỡ'},
        ),
        migrations.AlterModelOptions(
            name='storepolicy',
            options={'verbose_name': 'Chính sách cửa hàng', 'verbose_name_plural': 'Chính sách cửa hàng'},
        ),
    ]
