# Generated by Django 5.1.1 on 2026-04-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
            ],
            options={
                'verbose_name': 'Báo cáo doanh thu',
                'verbose_name_plural': 'Báo cáo doanh thu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
    ]
