# Generated by Django 5.1.1 on 2026-04-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_review_options_alter_sale_options_and_more'),
        ('products', '0011_salesreport'),
    ]

    operations = [
    ]
