# Generated by Django 5.1.1 on 2026-05-03 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20260424_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Giảm theo phần trăm (%)'), ('fixed', 'Giảm theo số tiền cố định (VND)')], default='percent', max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_value',
            field=models.PositiveIntegerField(default=10, help_text='Nếu theo %, nhập từ 1-100. Nếu theo số tiền, nhập số VND cần giảm.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Giá trị giảm'),
        ),
    ]
