# Generated by Django 5.1.1 on 2026-06-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sale_discount_type_sale_discount_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho (Theo Size)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.size')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm (Size)',
                'verbose_name_plural': 'Biến thể sản phẩm (Size)',
                'unique_together': {('product', 'size')},
            },
        ),
    ]
