# Generated by Django 5.1.1 on 2026-06-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/', verbose_name='Ảnh đánh giá'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Đã mua hàng'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Danh sách yêu thích',
                'verbose_name_plural': 'Danh sách yêu thích',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
